# Generated by Django 5.2.17 on 2026-08-13 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], max_length=10)),
                ('transfer_kind', models.CharField(blank=True, choices=[('account_to_account', 'Account to account'), ('to_nowhere', 'To nowhere'), ('from_nowhere', 'From nowhere')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('next_occurrence_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('repeat_rule', models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=10)),
                ('autocommit', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.CharField(default='RUB', max_length=3)),
                ('last_committed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_transactions', to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category')),
                ('tags', models.ManyToManyField(blank=True, to='ledger.tag')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_incoming', to='ledger.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_occurrence_date', 'id'],
            },
        ),
    ]
